# <a id='toc1_'></a>[Rozdział 2. Wektory, macierze i tablice wielowymiarowe](#toc0_)

**Table of contents**<a id='toc0_'></a>    
- [Rozdział 2. Wektory, macierze i tablice wielowymiarowe](#toc1_)    
  - [Typ tablicowy NumPy](#toc1_1_)    
  - [Typy danych](#toc1_2_)    
    - [Konwersja typów w wyniku działań](#toc1_2_1_)    
    - [Część rzeczywista i urojona](#toc1_2_2_)    
  - [Tworzenie tablic](#toc1_3_)    
    - [Tablice stworzone na podstawie list i innych obiektów tablicopodobnych](#toc1_3_1_)    
    - [Tablice wypełnione stałymi wartościami](#toc1_3_2_)    
    - [Tablice wypełnione rosnącymi wartościami](#toc1_3_3_)    
    - [Tablice z wartościami rozmieszczonymi logarytmicznie](#toc1_3_4_)    
    - [Tablice z siatkami współrzędnych](#toc1_3_5_)    
    - [Tworzenie niezainicjalizowanych tablic](#toc1_3_6_)    
    - [Tworzenie tablic o cechach innych tablic](#toc1_3_7_)    
    - [Tworzenie macierzy](#toc1_3_8_)    
  - [Indeksowanie i zakresy](#toc1_4_)    
    - [Tablice jednowymiarowe](#toc1_4_1_)    
  - [Tablice wielowymiarowe](#toc1_5_)    
    - [Widoki](#toc1_5_1_)    
    - [Indeksowanie logiczne i fancy indexing](#toc1_5_2_)    
  - [Zmiana kształtu i rozmiaru](#toc1_6_)    
  - [Wyrażenia zwektoryzowane](#toc1_7_)    
    - [Operacje arytmetyczne](#toc1_7_1_)    
    - [Funkcje działające na elementach](#toc1_7_2_)    
    - [Funkcje agregujące](#toc1_7_3_)    
    - [Wyrażenia warunkowe i tablice wartości logicznych](#toc1_7_4_)    
    - [Operacje na zbiorach](#toc1_7_5_)    
    - [Operacje na tablicach](#toc1_7_6_)    
  - [Operacje macierzowe i wektorowe](#toc1_8_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

**Libraries:**

- [NumPy](https://numpy.org/)
- [SymPy](https://www.sympy.org/en/index.html)
- [Matplotlib](https://matplotlib.org/)
- [SciPy](https://scipy.org/)

## <a id='toc1_1_'></a>[Typ tablicowy NumPy](#toc0_)

In [1]:
import numpy as np

In [2]:
data = np.array([[1, 7], [3, 4], [5, 6]])

In [3]:
type(data)

numpy.ndarray

In [4]:
data

array([[1, 7],
       [3, 4],
       [5, 6]])

In [5]:
data.ndim

2

In [6]:
data.shape

(3, 2)

In [7]:
data.size

6

In [8]:
data.dtype

dtype('int32')

In [9]:
data.nbytes

24

## <a id='toc1_2_'></a>[Typy danych](#toc0_)

In [10]:
np.array([1, 2, 3], dtype=np.int8)

array([1, 2, 3], dtype=int8)

In [11]:
np.array([1, 2, 3], dtype=np.float64)

array([1., 2., 3.])

In [12]:
np.array([1, 2, 3], dtype=np.complex128)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [13]:
data = np.array([1, 2, 3], dtype=np.float16)

In [14]:
data

array([1., 2., 3.], dtype=float16)

In [15]:
data.dtype

dtype('float16')

In [16]:
data = np.array(data, dtype=np.int8)

In [17]:
data.dtype

dtype('int8')

In [18]:
data

array([1, 2, 3], dtype=int8)

In [19]:
data = np.array([1, 2, 3], dtype=np.float32)

In [20]:
data

array([1., 2., 3.], dtype=float32)

In [21]:
data = data.astype(np.int64)

In [22]:
data

array([1, 2, 3], dtype=int64)

### <a id='toc1_2_1_'></a>[Konwersja typów w wyniku działań](#toc0_)

In [23]:
d1 = np.array([1, 2, 3], dtype=float)

In [24]:
d2 = np.array([1, 2, 3], dtype=complex)

In [25]:
d1 + d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [26]:
(d1 + d2).dtype

dtype('complex128')

In [27]:
np.sqrt(np.array([-1, 0, 1])) # domyślnie tworzona jest tablica float

C:\Users\Antoni\AppData\Local\Temp\ipykernel_2076\1719704783.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(np.array([-1, 0, 1])) # domyślnie tworzona jest tablica float


array([nan,  0.,  1.])

In [28]:
np.sqrt(np.array([-1, 0, 1], dtype=complex))

array([0.+1.j, 0.+0.j, 1.+0.j])

### <a id='toc1_2_2_'></a>[Część rzeczywista i urojona](#toc0_)

In [29]:
data = np.array([1+3j, 2+5j, 3-2j], dtype=complex)

In [30]:
data

array([1.+3.j, 2.+5.j, 3.-2.j])

In [31]:
data.real

array([1., 2., 3.])

In [32]:
data.imag

array([ 3.,  5., -2.])

## <a id='toc1_3_'></a>[Tworzenie tablic](#toc0_)

### <a id='toc1_3_1_'></a>[Tablice stworzone na podstawie list i innych obiektów tablicopodobnych](#toc0_)

In [33]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [34]:
data.ndim

1

In [35]:
data.shape

(3,)

In [36]:
data = np.array([[1, 2], [3, 4]])

In [37]:
data.ndim

2

In [38]:
data.shape

(2, 2)

### <a id='toc1_3_2_'></a>[Tablice wypełnione stałymi wartościami](#toc0_)

In [39]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.ones(4)

array([1., 1., 1., 1.])

In [41]:
data = np.ones(4)

In [42]:
data.dtype

dtype('float64')

In [43]:
data = np.ones(4, dtype=np.int64)

In [44]:
data.dtype

dtype('int64')

In [45]:
x1 = 5.4 * np.ones(10)
x1

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [46]:
x2 = np.full(10, 5.4)
x2

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [47]:
x1 = np.empty(5)
x1

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.78020848e-306,
       2.22813120e-312])

In [48]:
x1.fill(3.0)
x1

array([3., 3., 3., 3., 3.])

In [49]:
x2 = np.full(5, 3.0)
x2

array([3., 3., 3., 3., 3.])

In [51]:
x = np.diag([1, 3, 5, 17])
x

array([[ 1,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  5,  0],
       [ 0,  0,  0, 17]])

### <a id='toc1_3_3_'></a>[Tablice wypełnione rosnącymi wartościami](#toc0_)

In [52]:
x = np.array([x**2 + x + 1. for x in range(0, 10, 1)])
x

array([ 1.,  3.,  7., 13., 21., 31., 43., 57., 73., 91.])

In [53]:
x = np.arange(0.0, 10, 1)
x = x**2 + x + 1
x

array([ 1.,  3.,  7., 13., 21., 31., 43., 57., 73., 91.])

In [54]:
x = np.linspace(0, 10, 11)
x = x**2 + x + 1
x

array([  1.,   3.,   7.,  13.,  21.,  31.,  43.,  57.,  73.,  91., 111.])

### <a id='toc1_3_4_'></a>[Tablice z wartościami rozmieszczonymi logarytmicznie](#toc0_)

In [55]:
np.logspace(0, 2, 5)  # 5 punktów danych pomiędzy 10**0=1 i 10**2=100

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

### <a id='toc1_3_5_'></a>[Tablice z siatkami współrzędnych](#toc0_)

In [56]:
x = np.array([-1, 0, 1])

In [57]:
y = np.array([-2, 0, 2])

In [58]:
X, Y = np.meshgrid(x, y)

In [59]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [60]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [61]:
Z = (X + Y) ** 2

In [62]:
Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]])

### <a id='toc1_3_6_'></a>[Tworzenie niezainicjalizowanych tablic](#toc0_)

In [119]:
np.empty(3, dtype=float)

array([0., 0., 0.])

### <a id='toc1_3_7_'></a>[Tworzenie tablic o cechach innych tablic](#toc0_)

In [120]:
def f(x):
    y = np.ones_like(x)
    # Jakieś obliczenia z użyciem x i y 
    return y


### <a id='toc1_3_8_'></a>[Tworzenie macierzy](#toc0_)

In [121]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [122]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [123]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [66]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

## <a id='toc1_4_'></a>[Indeksowanie i zakresy](#toc0_)

### <a id='toc1_4_1_'></a>[Tablice jednowymiarowe](#toc0_)

In [124]:
a = np.arange(0, 11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [125]:
a[0]  # Pierwszy element

0

In [126]:
a[-1] # Ostatni element

10

In [127]:
a[4]  # Piąty element (dostępny pod indeksem 4)

4

In [135]:
a[3:7]

array([3, 4, 5, 6])

In [136]:
a[1:7:2]

array([1, 3, 5])

In [137]:
a[:5]

array([0, 1, 2, 3, 4])

In [139]:
a[-3:]

array([ 8,  9, 10])

In [140]:
a[::-2]


array([10,  8,  6,  4,  2,  0])

## <a id='toc1_5_'></a>[Tablice wielowymiarowe](#toc0_)

In [152]:
A = np.fromfunction(lambda m, n: n + 10 * m, (3, 5), dtype=int)
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [153]:
A = np.fromfunction(lambda m, n: np.sin(n) + np.e ** m, (3, 5), dtype=int)
A

array([[1.        , 1.84147098, 1.90929743, 1.14112001, 0.2431975 ],
       [2.71828183, 3.55975281, 3.62757926, 2.85940184, 1.96147933],
       [7.3890561 , 8.23052708, 8.29835353, 7.53017611, 6.6322536 ]])

In [155]:
A[:, 2]  # 3 kolumna

array([1.90929743, 3.62757926, 8.29835353])

In [156]:
A[1, :]  # Drugi wiersz

array([2.71828183, 3.55975281, 3.62757926, 2.85940184, 1.96147933])

In [159]:
A[:3, :3]

array([[1.        , 1.84147098, 1.90929743],
       [2.71828183, 3.55975281, 3.62757926],
       [7.3890561 , 8.23052708, 8.29835353]])

In [162]:
A[:2, 1:3]  

array([[1.84147098, 1.90929743],
       [3.55975281, 3.62757926]])

In [163]:
A[::2, ::2] # Co drugi element począwszy od elementu [0, 0] 

array([[1.        , 1.90929743, 0.2431975 ],
       [7.3890561 , 8.29835353, 6.6322536 ]])

In [164]:
A[::2, ::3]  # Elementy z co drugiego wiersza i co trzeciej kolumny począwszy od elementu [1, 1] 

array([[1.        , 1.14112001],
       [7.3890561 , 7.53017611]])

### <a id='toc1_5_1_'></a>[Widoki](#toc0_)

In [173]:
A = np.fromfunction(lambda m, n: n + 10 * m, (6, 6), dtype=int)
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [174]:
B = A[1:5, 1:5]
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [175]:
B[:, :] = 0
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [176]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [178]:
C = B[1:3, 1:3].copy()

In [179]:
C

array([[0, 0],
       [0, 0]])

In [180]:
C[:, :] = 1  # Zmiana wartości w tablicy C nie wpływa na zawartość tablicy B, ponieważ C jest kopią widoku B[1:3, 1:3]

In [181]:
C

array([[1, 1],
       [1, 1]])

In [182]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### <a id='toc1_5_2_'></a>[Indeksowanie logiczne i fancy indexing](#toc0_)

In [183]:
A = np.linspace(0, 1, 11)
A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [189]:
A[np.array([1, 6, 4])]

array([0.1, 0.6, 0.4])

In [190]:
A[[1, 6, 4]] # Ten sam efekt można uzyskać z wykorzystaniem listy

array([0.1, 0.6, 0.4])

In [191]:
A > 0.5 

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [192]:
A[A > 0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [207]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [208]:
indices = [2, 4, 6]

In [209]:
B = A[indices]
B

array([2, 4, 6])

In [210]:
B[0] = -1  # To przypisanie nie wpływa na wartości w A

In [211]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [214]:
A[indices] = -1 # To przypisanie wpływa na wartości w A

In [215]:
A

array([ 0,  1, -1,  3, -1,  5, -1,  7,  8,  9])

In [216]:
A = np.arange(10)

In [217]:
B = A[A > 5]

In [218]:
B[0] = -1  # To przypisanie nie wpływa na wartości w A

In [219]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [220]:
A[A > 5] = -1 # To przypisanie wpływa na wartości w A

In [221]:
A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

## <a id='toc1_6_'></a>[Zmiana kształtu i rozmiaru](#toc0_)

In [249]:
data = np.array([[1, 2], [3, 4]])
data

array([[1, 2],
       [3, 4]])

In [246]:
data = np.reshape(data, (1, 4))
data

array([[1, 2, 3, 4]])

In [250]:
data = data.reshape(4)
data

array([1, 2, 3, 4])

In [251]:
data = np.reshape(data, (2, 2))
data

array([[1, 2],
       [3, 4]])

In [254]:
data = np.array([[1, 2], [3, 4]])
data

array([[1, 2],
       [3, 4]])

In [255]:
data.flatten()

array([1, 2, 3, 4])

In [256]:
data.flatten().shape

(4,)

In [257]:
data = np.arange(0, 5)

In [258]:
column = data[:, np.newaxis]

In [259]:
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [260]:
row = data[np.newaxis, :]

In [261]:
row

array([[0, 1, 2, 3, 4]])

In [262]:
data = np.arange(5)

In [263]:
data

array([0, 1, 2, 3, 4])

In [264]:
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [265]:
data = np.arange(5)

In [266]:
data

array([0, 1, 2, 3, 4])

In [267]:
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [268]:
data = data[:, np.newaxis]

In [269]:
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

## <a id='toc1_7_'></a>[Wyrażenia zwektoryzowane](#toc0_)

### <a id='toc1_7_1_'></a>[Operacje arytmetyczne](#toc0_)

In [270]:
x = np.array([[1, 2], [3, 4]]) 

In [271]:
y = np.array([[5, 6], [7, 8]])

In [272]:
x + y

array([[ 6,  8],
       [10, 12]])

In [273]:
y - x

array([[4, 4],
       [4, 4]])

In [274]:
x * y

array([[ 5, 12],
       [21, 32]])

In [275]:
y / x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [276]:
x * 2

array([[2, 4],
       [6, 8]])

In [277]:
2 ** x

array([[ 2,  4],
       [ 8, 16]], dtype=int32)

In [278]:
y / 2

array([[2.5, 3. ],
       [3.5, 4. ]])

In [279]:
(y / 2).dtype

dtype('float64')

In [280]:
x = np.array([1, 2, 3, 4]).reshape(2,2)
x

array([[1, 2],
       [3, 4]])

In [281]:
z = np.array([1, 2, 3, 4])
z

array([1, 2, 3, 4])

In [282]:
x / z

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

In [283]:
z = np.array([[2, 4]])

In [284]:
z

array([[2, 4]])

In [285]:
z.shape

(1, 2)

In [286]:
x / z

array([[0.5, 0.5],
       [1.5, 1. ]])

In [287]:
zz = np.concatenate([z, z], axis=0)

In [288]:
zz

array([[2, 4],
       [2, 4]])

In [289]:
x / zz

array([[0.5, 0.5],
       [1.5, 1. ]])

In [290]:
z = np.array([[2], [4]])

In [291]:
z.shape

(2, 1)

In [292]:
x / z

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [293]:
zz = np.concatenate([z, z], axis=1)

In [294]:
zz

array([[2, 2],
       [4, 4]])

In [295]:
x / zz

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [299]:
x = np.array([[1, 3], [2, 4]])
x = x + y # Operacja musi zaalokować dodatkowe miejsce na wynik, który później przypisuje do x
x

array([[ 6,  9],
       [ 9, 12]])

In [300]:
x = np.array([[1, 3], [2, 4]])
x += y # Operator działania w miejscu - nie allokuje dodatkowego miejsca w pamięci!!
x

array([[ 6,  9],
       [ 9, 12]])

### <a id='toc1_7_2_'></a>[Funkcje działające na elementach](#toc0_)

In [307]:
x = np.linspace(-1, 1, 11)
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [308]:
y = np.sin(np.pi * x)
y

array([-1.22464680e-16, -5.87785252e-01, -9.51056516e-01, -9.51056516e-01,
       -5.87785252e-01,  0.00000000e+00,  5.87785252e-01,  9.51056516e-01,
        9.51056516e-01,  5.87785252e-01,  1.22464680e-16])

In [309]:
np.round(y, decimals=4)

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [310]:
np.add(np.sin(x) ** 2, np.cos(x) ** 2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [311]:
np.sin(x) ** 2 + np.cos(x) ** 2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [312]:
def heaviside(x):
    return 1 if x > 0 else 0

In [313]:
heaviside(-1)

0

In [314]:
heaviside(1.5)

1

In [315]:
x = np.linspace(-5, 5, 11)

In [316]:
heaviside(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [317]:
heaviside = np.vectorize(heaviside)

In [318]:
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [319]:
def heaviside(x):
    return 1.0 * (x > 0)

### <a id='toc1_7_3_'></a>[Funkcje agregujące](#toc0_)

In [321]:
data = np.random.normal(size=(15,15))

In [322]:
np.mean(data)

0.023176467404429735

In [323]:
data.mean()

0.023176467404429735

In [324]:
data = np.random.normal(size=(3, 3, 3))
data

array([[[-1.54780068, -4.27495473, -1.07846911],
        [-0.81809793,  0.79656067, -0.41646319],
        [ 0.06633152, -1.08180684, -0.36845449]],

       [[-0.39336791, -0.16634486,  0.10720024],
        [ 0.35823456,  0.63161943,  0.07115713],
        [ 1.02651017, -0.48666098, -1.91371483]],

       [[ 0.23569306,  1.01153414,  0.49319913],
        [-0.60553178, -0.43362472, -1.13845684],
        [-0.5484588 , -1.00768028, -0.25071899]]])

In [325]:
data.sum(axis=0).shape

(3, 3)

In [326]:
data.sum(axis=(0, 2)).shape

(3,)

In [327]:
data.sum()

-11.732566897622709

In [328]:
data = np.arange(1,10).reshape(3,3)

In [329]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [330]:
data.sum()

45

In [331]:
data.sum(axis=0)

array([12, 15, 18])

In [332]:
data.sum(axis=1)

array([ 6, 15, 24])

### <a id='toc1_7_4_'></a>[Wyrażenia warunkowe i tablice wartości logicznych](#toc0_)

In [333]:
a = np.array([1, 2, 3, 4])

In [334]:
b = np.array([4, 3, 2, 1])

In [335]:
a < b

array([ True,  True, False, False])

In [336]:
np.all(a < b)

False

In [337]:
np.any(a < b)

True

In [338]:
if np.all(a < b):
    print("Wszystkie elementy w a są mniejsze niż odpowiadające im elementy w b.")
elif np.any(a < b):
    print("Niektóre z elementów w a są mniejsze niż odpowiadające im elementy w b.")
else:
    print("Wszystkie elementy w b są mniejsze niż odpowiadające im elementy w a.")

Niektóre z elementów w a są mniejsze niż odpowiadające im elementy w b.


In [339]:
x = np.array([-2, -1, 0, 1, 2])

In [340]:
x > 0

array([False, False, False,  True,  True])

In [341]:
1 * (x > 0)

array([0, 0, 0, 1, 1])

In [342]:
x * (x > 0)

array([0, 0, 0, 1, 2])

In [343]:
def pulse(x, position, height, width):
    return height * (x >= position) * (x <= (position + width))

In [344]:
x = np.linspace(-5, 5, 11)

In [345]:
pulse(x, position=-2, height=1, width=5)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0])

In [346]:
pulse(x, position=1, height=1, width=5)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [347]:
def pulse(x, position, height, width):
    return height * np.logical_and(x >= position, x <= (position + width))

In [349]:
x = np.linspace(-4, 4, 9)
x

array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [351]:
np.where(x < 0, x**2, x**3)

array([16.,  9.,  4.,  1.,  0.,  1.,  8., 27., 64.])

In [352]:
np.select([x < -1, x < 2, x >= 2],
          [x**2  , x**3 , x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [353]:
np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2], 
          [x**2,    x**3,    x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [354]:
x[abs(x) > 2]

array([-4., -3.,  3.,  4.])

In [355]:
np.nonzero(abs(x) > 2)

(array([0, 1, 7, 8], dtype=int64),)

In [356]:
x[np.nonzero(abs(x) > 2)]

array([-4., -3.,  3.,  4.])

### <a id='toc1_7_5_'></a>[Operacje na zbiorach](#toc0_)

In [357]:
a = np.unique([1,2,3,3])
a

array([1, 2, 3])

In [358]:
b = np.unique([2,3,4,4,5,6,5])
b

array([2, 3, 4, 5, 6])

In [359]:
np.in1d(a, b)

array([False,  True,  True])

In [360]:
1 in a

True

In [361]:
1 in b

False

In [362]:
np.all(np.in1d(a, b))

False

In [363]:
np.union1d(a, b)

array([1, 2, 3, 4, 5, 6])

In [364]:
np.intersect1d(a, b)

array([2, 3])

In [365]:
np.setdiff1d(a, b)

array([1])

In [366]:
np.setdiff1d(b, a)

array([4, 5, 6])

### <a id='toc1_7_6_'></a>[Operacje na tablicach](#toc0_)

In [368]:
data = np.arange(9).reshape(3, 3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [369]:
np.transpose(data)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [370]:
data = np.random.randn(1, 2, 3, 4, 5)

In [371]:
data.shape

(1, 2, 3, 4, 5)

In [372]:
data.T.shape

(5, 4, 3, 2, 1)

## <a id='toc1_8_'></a>[Operacje macierzowe i wektorowe](#toc0_)

In [382]:
A = np.arange(1, 7).reshape(2, 3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
B = np.arange(1, 7).reshape(3, 2)
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [384]:
np.dot(A,B)

array([[22, 28],
       [49, 64]])

In [385]:
A @ B

array([[22, 28],
       [49, 64]])

In [386]:
A.dot(B)

array([[22, 28],
       [49, 64]])

In [387]:
np.dot(B, A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [388]:
B @ A

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [389]:
B.dot(A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [390]:
A = np.arange(9).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [391]:
x = np.arange(3)
x

array([0, 1, 2])

In [392]:
np.dot(A, x)

array([ 5, 14, 23])

In [393]:
A.dot(x)

array([ 5, 14, 23])

In [394]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)

In [395]:
Ap = B @ A @ np.linalg.inv(B)
Ap

array([[-2.55471346,  0.31157162,  1.71698956],
       [-9.51414086,  0.63198777,  7.56346816],
       [-4.68293598,  0.55817891,  3.40871261]])

In [396]:
Ap = np.dot(B, np.dot(A, np.linalg.inv(B)))
Ap

array([[-2.55471346,  0.31157162,  1.71698956],
       [-9.51414086,  0.63198777,  7.56346816],
       [-4.68293598,  0.55817891,  3.40871261]])

In [397]:
Ap = B.dot(A.dot(np.linalg.inv(B)))
Ap

array([[-2.55471346,  0.31157162,  1.71698956],
       [-9.51414086,  0.63198777,  7.56346816],
       [-4.68293598,  0.55817891,  3.40871261]])

In [398]:
A = np.matrix(A)

In [399]:
B = np.matrix(B)

In [401]:
Ap = B * A * B.I
Ap

matrix([[-2.55471346,  0.31157162,  1.71698956],
        [-9.51414086,  0.63198777,  7.56346816],
        [-4.68293598,  0.55817891,  3.40871261]])

In [402]:
A = np.asmatrix(A)

In [403]:
B = np.asmatrix(B)

In [404]:
Ap = B * A * B.I
Ap

matrix([[-2.55471346,  0.31157162,  1.71698956],
        [-9.51414086,  0.63198777,  7.56346816],
        [-4.68293598,  0.55817891,  3.40871261]])

In [405]:
Ap = np.asarray(Ap)

In [406]:
Ap

array([[-2.55471346,  0.31157162,  1.71698956],
       [-9.51414086,  0.63198777,  7.56346816],
       [-4.68293598,  0.55817891,  3.40871261]])

In [407]:
np.inner(x, x)

5

In [408]:
np.dot(x, x)

5

In [409]:
y = x[:, np.newaxis]

In [410]:
y

array([[0],
       [1],
       [2]])

In [411]:
np.dot(y.T, y)

array([[5]])

In [412]:
x = np.array([1, 2, 3])

In [413]:
np.outer(x, x) 

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [414]:
np.kron(x, x) 

array([1, 2, 3, 2, 4, 6, 3, 6, 9])

In [415]:
np.kron(x[:, np.newaxis], x[np.newaxis, :])

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [416]:
np.kron(np.ones((2,2)), np.identity(2))

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [417]:
np.kron(np.identity(2), np.ones((2,2)))

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [418]:
x = np.array([1, 2, 3, 4])

In [419]:
y = np.array([5, 6, 7, 8])

In [420]:
np.einsum("n,n", x, y)

70

In [421]:
np.inner(x, y)

70

In [422]:
A = np.arange(9).reshape(3, 3)

In [423]:
B = A.T

In [424]:
np.einsum("mk,kn", A, B)

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

In [425]:
np.alltrue(np.einsum("mk,kn", A, B) == np.dot(A, B))

True